In [67]:
import numpy as np
import matplotlib.pyplot as plt
import torch

In [68]:
x = np.array([[0, 0, 1],
               [0, 1, 1],
               [1, 0, 1],
               [1, 1, 1]])

In [69]:
y = np.array([[0],
             [1],
             [1],
             [0]])

In [70]:
alpha = 0.05
batch = 60000

In [71]:
np.random.seed(1)

In [72]:
# initalize tghe weights randomly 

w0 = 2*np.random.random((3,4)) -1 
w1 = 2*np.random.random((4,1))

In [73]:
w0

array([[-0.16595599,  0.44064899, -0.99977125, -0.39533485],
       [-0.70648822, -0.81532281, -0.62747958, -0.30887855],
       [-0.20646505,  0.07763347, -0.16161097,  0.370439  ]])

In [74]:
#eq #1 

def sigmoid(z):
  return 1 / (1 + np.exp( -z ))

In [75]:
# sigmoid prime eq # 2
def sigmoid_prime(z):
  return (z * (1 - z))

In [76]:
#burada bir mini batch algoritması tanımladım
#mini batch gradient descent, training set'in model errorlarını ve ve model ceofficient'larını hesaplamak için kullanılan bir optimization algoritmasıdır.
batch_size=2
mini_batches = []
data = np.hstack((x, y))
np.random.shuffle(data)
#n_minibatches = data.shape[0] // batch_size
i = 0
  
for i in range(batch_size):
  mini_batch = data[i * batch_size:(i + 1)*batch_size, :]
  X_mini = mini_batch[:, :-1]
  Y_mini = mini_batch[:, -1].reshape((-1, 1))
  mini_batches.append((X_mini, Y_mini))

In [77]:
#ilk for döngüsünün içine ikinci bir for döngüsü ekledim
#bunun sebebi ise, yukarıda yazmış olduğum mini-batch algoritmasının array'ini kullanabilmek.
#mini batch algoritmasındaki array'imi bu döngüye koyarak her değer için dolaştırıyorum ve benden istenen değerleri elde etmiş oluyorum.
for cntr in range(batch):
  for mbatch in mini_batches:
    batch_x, batch_y = mbatch
    n = batch_x.shape[0]
    a0 = batch_x 
    z1 = np.dot(a0, w0)
    a1 = sigmoid(z1)
    z2 = np.dot(a1, w1)

    # second layer activation function values 
    a2 = sigmoid(z2)

    l2_error = (a2 - batch_y)/n

    if cntr % 1000 ==0:
      print("Error: ", str(np.mean(np.mean(np.abs(l2_error)))))

    # eq 6
    l2_delta = l2_error * sigmoid_prime(a2)

    l1_error = l2_delta.dot(w1.T)

    # eq 7 
    l1_delta = l1_error * sigmoid_prime(a1)

    # eq #  5 
    w1 -= alpha*a1.T.dot(l2_delta)
    w0 -= alpha*a0.T.dot(l1_delta)

Error:  0.24920560169184325
Error:  0.2510545185918266
Error:  0.23841176962712507
Error:  0.25761647212434235
Error:  0.22997552767665957
Error:  0.2611956359518171
Error:  0.21882057615769107
Error:  0.26367659286813516
Error:  0.20255554401996145
Error:  0.265168981285434
Error:  0.1803679648861115
Error:  0.2649266413086337
Error:  0.1550137212475366
Error:  0.26158622642918616
Error:  0.13197372067620278
Error:  0.25385238256471093
Error:  0.11466691631029949
Error:  0.24041697618791338
Error:  0.10404564516267863
Error:  0.21722742314374807
Error:  0.09836842240789151
Error:  0.17918870432546558
Error:  0.08990561052272264
Error:  0.1439988171019808
Error:  0.07943232849949344
Error:  0.11849057315095565
Error:  0.06972746735950451
Error:  0.10020378974398647
Error:  0.061657321091369593
Error:  0.0867944865891477
Error:  0.055149054305742115
Error:  0.0766828743137756
Error:  0.04990461523927081
Error:  0.06884731485441467
Error:  0.045635580693540415
Error:  0.06262374926569397

In [78]:
print("after training:\n")
print(a2)

after training:

[[0.97014657]
 [0.04173737]]


In [79]:
#Bu kod parçacığı aslında q-1 için kullanıldı ancak soruda bizden bu değerleri tekrar train etmemiz istendiği için tekrar bu kod parçacağını kullandık.
#çıktların değişmesinin sebebi neural network'ümüzü farklı bir şekilde train etmemizden kaynaklanmaktadır.

x1 = [1,1,0]
x2 = [1,1,1]

def testNN(myTester):

  a0 = myTester 
  z1 = np.dot(a0, w0)
  a1 = sigmoid(z1)
  z2 = np.dot(a1, w1)
  a2 = sigmoid(z2)

  return a2

#bizden istenilen testNN fonksiyonunu oluşturduk
#fonksiyon bir adet parametre alıyor, o parametre değeri bize verilen x1 ve x2 değerlerini test etmek için kullanılıyor.

myTest1 = testNN(x1)
myTest2 = testNN(x2)

print("x1 -> y1:", myTest1)
print("-------------------\n")
print("x2 -> y2:", myTest2)

#burada ise x1 ve x2 değerlerini testNN fonksiyonuna yolluyorum, return değeri bana elde etmek istediğim sonucu veriyor ve ekrana print ediyorum.


print("-------------------\n")

print("after training:\n")
print(a2)

x1 -> y1: [0.11968302]
-------------------

x2 -> y2: [0.04173604]
-------------------

after training:

[[0.97014657]
 [0.04173737]]
